import {useEffect,useState} from 'react'
import {motion,useReducedMotion} from 'framer-motion'
import {Activity,ArrowDown,ArrowRight,Check,ChevronRight,Database,ExternalLink,Globe,LockKeyhole,ScanSearch,Shield,ShieldAlert,ShieldCheck,Terminal,TriangleAlert,Zap} from 'lucide-react'
import HeroScene from './components/HeroScene.jsx'

const API_BASE_URL=(import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8010').replace(/\/+$/,'')
const apiUrl=(path)=>`${API_BASE_URL}${path}`
const groups={
 'URL Structure':['URLLength','path_length','query_length','fragment_length','NoOfSubDomain'],
 'Domain':['DomainLength','TLDLength','TLD','IsDomainIP','has_punycode','has_url_shortener'],
 'Security':['IsHTTPS','has_port'],
 'Obfuscation':['HasObfuscation','NoOfObfuscatedChar','ObfuscationRatio','num_encoded_chars'],
 'Characters':['NoOfLettersInURL','LetterRatioInURL','NoOfDegitsInURL','DegitRatioInURL','NoOfEqualsInURL','NoOfQMarkInURL','NoOfAmpersandInURL','NoOfOtherSpecialCharsInURL','SpacialCharRatioInURL','num_dots','num_hyphens','num_underscores','num_slashes','num_at','num_hashes','num_percent','num_colons','num_semicolons'],
 'Statistics':['url_entropy','max_repeat_ratio','num_suspicious_keywords']
}
const featureLabels={URLLength:'URL length',DomainLength:'Domain length',TLDLength:'TLD length',TLD:'Top-level domain',NoOfSubDomain:'Subdomains',HasObfuscation:'Obfuscation present',NoOfObfuscatedChar:'Obfuscation characters',ObfuscationRatio:'Obfuscation ratio',NoOfLettersInURL:'Letters',LetterRatioInURL:'Letter ratio',NoOfDegitsInURL:'Digits',DegitRatioInURL:'Digit ratio',NoOfEqualsInURL:'Equals signs',NoOfQMarkInURL:'Question marks',NoOfAmpersandInURL:'Ampersands',NoOfOtherSpecialCharsInURL:'Other special characters',SpacialCharRatioInURL:'Special character ratio',IsDomainIP:'IP address host',IsHTTPS:'HTTPS',num_dots:'Dots',num_hyphens:'Hyphens',num_underscores:'Underscores',num_slashes:'Slashes',num_at:'At signs',num_hashes:'Hashes',num_percent:'Percent signs',num_colons:'Colons',num_semicolons:'Semicolons',url_entropy:'URL entropy',path_length:'Path length',query_length:'Query length',fragment_length:'Fragment length',has_port:'Custom port',has_punycode:'Punycode',has_url_shortener:'Known shortener pattern',num_encoded_chars:'Encoded characters',max_repeat_ratio:'Maximum repeated character ratio',num_suspicious_keywords:'Suspicious URL keywords'}
const steps=[['01','Enter URL','Provide a URL string to analyze.'],['02','Normalize URL','Canonicalize the scheme, host and default port.'],['03','Extract URL features','Measure lexical and structural signals only.'],['04','Preprocess','Transform the feature vector with the fitted pipeline.'],['05','Machine learning','Score with the selected trained classifier.'],['06','Prediction','Return the class, probability and feature values.']]

function App(){
 const reduced=useReducedMotion();const [url,setUrl]=useState('');const [result,setResult]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [info,setInfo]=useState(null);const [apiState,setApiState]=useState('checking')
 useEffect(()=>{let live=true;const refresh=()=>Promise.all([fetch(apiUrl('/api/health')),fetch(apiUrl('/api/model_info'))]).then(async([healthResponse,infoResponse])=>{if(!healthResponse.ok||!infoResponse.ok)throw Error('API unavailable');const health=await healthResponse.json();const data=await infoResponse.json();if(health.status!=='healthy')throw Error('API unavailable');return data}).then(data=>{if(live){setInfo(data);setApiState('online')}}).catch(()=>{if(live)setApiState('offline')});refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer)}},[])
 async function analyze(e){e.preventDefault();setError('');setResult(null);if(!url.trim()){setError('Enter a URL to analyze.');return}setLoading(true);try{const res=await fetch(apiUrl('/api/predict'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()})});const body=await res.json();if(!res.ok){const detail=Array.isArray(body.detail)?body.detail.map(item=>item.msg).join(' • '):body.detail;throw Error(detail||'Unable to analyze that URL.')}setResult(body)}catch(err){setError(err.message.includes('Failed to fetch')?'Cannot reach the configured PhishGuard API. Check that it is running and try again.':err.message)}finally{setLoading(false)}}
 const number=(v)=>typeof v==='number'?(Number.isInteger(v)?v.toLocaleString():v.toFixed(3)):String(v)
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Shield size={19}/></span><span>PHISH<span className="brand-accent">GUARD</span></span></a><nav><a href="#analyzer">Analyzer</a><a href="#method">How it works</a><a href="#model">Model</a></nav><div className="api-badge"><i className={apiState==='online'?'online':apiState==='offline'?'offline':''}/>{apiState==='online'?'SYSTEM ONLINE':apiState==='checking'?'CONNECTING':'API OFFLINE'}</div></header>
  <section className="hero wrap" id="top"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> URL INTELLIGENCE <span className="eyebrow-dot">•</span> MACHINE LEARNING</div><h1>See the signal.<br/><span>Stop the threat.</span></h1><p className="hero-sub">AI-Powered Phishing URL Detection</p><p className="hero-desc">Inspect the structure behind a link with a trained machine-learning model. URL-only analysis means the submitted website is never opened or contacted.</p><div className="hero-actions"><a className="button primary" href="#analyzer">Analyze a URL <ArrowRight size={16}/></a><a className="text-link" href="#method">Explore the process <ArrowDown size={15}/></a></div><div className="hero-proof"><span><LockKeyhole size={15}/> No website requests</span><span><Zap size={15}/> API-backed inference</span><span><Activity size={15}/> Feature transparency</span></div></div><div className="hero-visual"><div className="visual-glow"/><HeroScene/><div className="scene-label"><span className="pulse-dot"/> STATIC URL ANALYSIS <span className="scene-coords">PG—01</span></div><div className="orbit-tag tag-a">URL PARSED <Check size={12}/></div><div className="orbit-tag tag-b"><span/> THREAT SIGNALS</div></div><div className="hero-bottom"><span>URL-ONLY STATIC ANALYSIS</span><span>01 / 03 <span className="muted">— INTELLIGENCE OVER ASSUMPTION</span></span></div></section>
  <section className="analyzer-section wrap" id="analyzer"><div className="section-kicker">01 <span/> LIVE URL ANALYZER</div><div className="analyzer-grid"><div><h2>Inspect a link.<br/><span>Understand its signals.</span></h2><p className="section-copy">Paste a URL to extract its structure and run the trained model. PhishGuard never visits the destination.</p><div className="privacy-note"><LockKeyhole size={16}/><span>PRIVATE BY DESIGN <small>The submitted URL is sent to the configured PhishGuard API for analysis.</small></span></div></div><div className="analyzer-card"><div className="card-head"><div><ScanSearch size={17}/><span>URL ANALYSIS</span></div><span className="card-ref">PG / ANALYZE</span></div><form onSubmit={analyze} noValidate><label htmlFor="url-entry">Enter a URL to analyze</label><div className={`input-wrap ${error?'input-error':''}`}><Globe size={18}/><input id="url-entry" value={url} onChange={e=>{setUrl(e.target.value);setResult(null);setError('')}} placeholder="https://example.com/login" maxLength={2048} autoComplete="url"/><span className="input-suffix">HTTPS · HTTP</span></div><button className="button primary submit" disabled={loading}>{loading?<><span className="spinner"/> Analyzing...</>:result?'Analysis Complete':<>Analyze URL <ArrowRight size={16}/></>}</button>{error&&<div className="error-message" role="alert"><TriangleAlert size={16}/>{error}</div>}<p className="form-foot"><LockKeyhole size={13}/> Submitted URL is parsed as text. No network request is made to it.</p></form></div></div>
   {result&&<motion.div initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} className={`result-card ${result.label===0?'risk':'safe'}`}><div className="result-top"><div className="result-icon">{result.label===0?<ShieldAlert/>:<ShieldCheck/>}</div><div className="result-title"><div className="section-kicker">ML-BASED PREDICTION <span className="result-time">{new Date().toLocaleString()}</span></div><h3>{result.label===0?'POTENTIAL PHISHING URL':'LEGITIMATE URL'}</h3><p>Technical class: {result.technical_class}</p></div><div className="confidence"><span>MODEL CONFIDENCE</span><strong>{(result.confidence*100).toFixed(1)}<small>%</small></strong></div></div><div className="result-meta"><span>MODEL <b>{result.model}</b></span><span>ML RISK INDICATOR <b className={result.label===0?'risk-text':'safe-text'}>{result.label===0?'ELEVATED':'LOWER'}</b></span><span>CLASS <b>{result.label}</b></span></div><p className="confidence-note">Model confidence is a classifier probability and is not a guarantee that the website is safe or malicious.</p><div className="feature-breakdown"><div className="breakdown-head"><h4>Extracted URL features</h4><span>{Object.keys(result.features).length} SIGNALS</span></div><div className="feature-groups">{Object.entries(groups).map(([group,keys])=><div className="feature-group" key={group}><h5>{group}</h5><div className="feature-list">{keys.map(key=><div className="feature-row" key={key}><span>{featureLabels[key]||key}</span><b>{number(result.features[key])}</b></div>)}</div></div>)}</div></div></motion.div>}
  </section>
  <section className="workflow-section" id="method"><div className="wrap"><div className="section-kicker">02 <span/> UNDER THE HOOD</div><div className="section-heading"><h2>A clear path from<br/><span>URL to insight.</span></h2><p>One transparent pipeline. Each stage operates on the URL string and its derived features.</p></div><div className="steps">{steps.map(([n,title,desc],i)=><motion.div key={n} className="step" initial={reduced?false:{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:reduced?0:i*.07}}><div className="step-top"><span>{n}</span><ChevronRight size={15}/></div><div className="step-icon">{[<Terminal/>,<Globe/>,<ScanSearch/>,<Activity/>,<Zap/>,<ShieldCheck/>][i]}</div><h3>{title}</h3><p>{desc}</p></motion.div>)}</div></div></section>
  <section className="model-section wrap" id="model"><div className="section-kicker">03 <span/> MODEL SNAPSHOT</div><div className="section-heading"><h2>Measured on<br/><span>held-out data.</span></h2><p>Live metadata from the locally trained model. Performance figures describe a test set and are not a safety guarantee.</p></div>{info?<><div className="metrics-row"><Metric label="ACCURACY" value={info.accuracy}/><Metric label="PRECISION" value={info.precision}/><Metric label="RECALL" value={info.recall}/><Metric label="F1 SCORE" value={info.f1}/></div><div className="model-details"><div className="detail-card"><div className="detail-icon"><Database/></div><div><span>TRAINING DATASET</span><strong>{info.dataset}</strong><small>{info.records.toLocaleString()} cleaned records · {info.features} URL features</small></div></div><div className="detail-card"><div className="detail-icon"><Shield/></div><div><span>SELECTED CLASSIFIER</span><strong>{info.model}</strong><small>{info.false_positives.toLocaleString()} false positives · {info.false_negatives.toLocaleString()} false negatives</small></div></div></div><div className="domain-note"><Activity size={16}/><span>DOMAIN-AWARE HOLDOUT <b>{(info.domain_aware.accuracy*100).toFixed(1)}% accuracy</b><small>{info.domain_aware.test_rows.toLocaleString()} held-out URLs from domains absent in training. Hostname overlap: {info.domain_aware.domain_overlap}.</small></span></div></>:<div className="offline-note">{apiState==='offline'?'Start the backend to view live model information.':'Loading model information…'}</div>}</section>
  <section className="limits-section"><div className="wrap limits-inner"><div className="limits-icon"><LockKeyhole/></div><div><div className="section-kicker">BUILT WITH CLEAR LIMITS</div><h2>Signals, not certainty.</h2><p>PhishGuard analyzes URL-derived features only. It does not visit or inspect the submitted website. Predictions may contain false positives and false negatives. HTTPS and domain extensions such as .com and .in are signals, not guarantees of legitimacy.</p></div></div></section>
  <footer className="footer wrap"><a className="brand" href="#top"><span className="brand-mark"><Shield size={17}/></span><span>PHISH<span className="brand-accent">GUARD</span></span></a><span>AI-BASED PHISHING URL DETECTION · EDUNET FOUNDATION MINI PROJECT</span><a href="#top" className="back-top">BACK TO TOP ↑</a></footer>
 </main>
}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{(value*100).toFixed(1)}<small>%</small></strong><div className="metric-track"><i style={{width:`${Math.min(100,value*100)}%`}}/></div></div>}
export default App
